import { db } from "../firebase";
import { doc, writeBatch } from "firebase/firestore";
import { type AppUser } from "./types";

const SEED_USERS: AppUser[] = [
  // PRODUCERS
  {
    uid: "prod_1",
    role: "producer",
    setupComplete: true,
    firstName: "Alex",
    lastName: "Rivers",
    artistName: "RiverBeats",
    name: "RiverBeats",
    dob: "1995-05-12",
    gender: "Male",
    imageUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    bio: "Specializing in atmospheric trap and lo-fi hip hop.",
    genres: ["Trap", "Lo-fi"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    contact: {
      email: "alex@riverbeats.com",
      phone: "555-0101",
      location: "Los Angeles, CA",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
  {
    uid: "prod_2",
    role: "producer",
    setupComplete: true,
    firstName: "Marcus",
    lastName: "Zen",
    artistName: "Zenith",
    name: "Zenith",
    dob: "1992-03-15",
    gender: "Male",
    imageUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    bio: "Grammy-nominated engineer. Tech-house and Techno only.",
    genres: ["Techno", "House"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    contact: {
      email: "marcus@zenith.io",
      phone: "555-0102",
      location: "Berlin, DE",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
  {
    uid: "prod_3",
    role: "producer",
    setupComplete: true,
    firstName: "Chloe",
    lastName: "Simmons",
    artistName: "C-BeatZ",
    name: "C-BeatZ",
    dob: "1997-08-22",
    gender: "Female",
    imageUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
    bio: "Hyperpop and experimental electronic producer.",
    genres: ["Hyperpop", "Electronic"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    contact: {
      email: "chloe@cbeatz.com",
      phone: "555-0103",
      location: "London, UK",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
  {
    uid: "prod_4",
    role: "producer",
    setupComplete: true,
    firstName: "David",
    lastName: "Chen",
    artistName: "D-Wave",
    name: "D-Wave",
    dob: "1990-11-30",
    gender: "Male",
    imageUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
    bio: "Cinematic scores and orchestral hybrid production.",
    genres: ["Cinematic", "Orchestral"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    contact: {
      email: "david@dwave.com",
      phone: "555-0104",
      location: "Vancouver, BC",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
  {
    uid: "prod_5",
    role: "producer",
    setupComplete: true,
    firstName: "Jordan",
    lastName: "Keys",
    artistName: "J-Soul",
    name: "J-Soul",
    dob: "1994-01-10",
    gender: "Other",
    imageUrl:
      "https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400",
    bio: "Neo-soul and Jazz fusion. I play live keys on every track.",
    genres: ["Neo-soul", "Jazz"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    contact: {
      email: "jordan@jsoul.com",
      phone: "555-0105",
      location: "Atlanta, GA",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },

  // ARTISTS
  {
    uid: "art_1",
    role: "artist",
    setupComplete: true,
    firstName: "Sarah",
    lastName: "Vocal",
    artistName: "SARA-H",
    name: "SARA-H",
    dob: "1998-11-20",
    gender: "Female",
    imageUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    bio: "R&B singer-songwriter looking for heavy bass.",
    genres: ["R&B", "Pop"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    contact: {
      email: "sarah@music.com",
      phone: "555-0106",
      location: "New York, NY",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
  {
    uid: "art_2",
    role: "artist",
    setupComplete: true,
    firstName: "Tariq",
    lastName: "Knight",
    artistName: "T-Flow",
    name: "T-Flow",
    dob: "1996-06-05",
    gender: "Male",
    imageUrl:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400",
    bio: "Lyricist focused on storytelling and conscious rap.",
    genres: ["Hip Hop", "Rap"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    contact: {
      email: "tariq@tflow.com",
      phone: "555-0107",
      location: "Chicago, IL",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
  {
    uid: "art_3",
    role: "artist",
    setupComplete: true,
    firstName: "Luna",
    lastName: "Grey",
    artistName: "LUNA",
    name: "LUNA",
    dob: "2000-02-14",
    gender: "Female",
    imageUrl:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400",
    bio: "Dream pop vocalist with a love for reverb and synths.",
    genres: ["Dream Pop", "Indie"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    contact: {
      email: "luna@grey.com",
      phone: "555-0108",
      location: "Portland, OR",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
  {
    uid: "art_4",
    role: "artist",
    setupComplete: true,
    firstName: "Elena",
    lastName: "Rossi",
    artistName: "E-Vocal",
    name: "E-Vocal",
    dob: "1993-09-18",
    gender: "Female",
    imageUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400",
    bio: "Classical crossover artist. Opera meets electronic.",
    genres: ["Classical", "Electronic"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    contact: {
      email: "elena@evocal.it",
      phone: "555-0109",
      location: "Rome, IT",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
  {
    uid: "art_5",
    role: "artist",
    setupComplete: true,
    firstName: "Zion",
    lastName: "Lee",
    artistName: "Zion",
    name: "Zion",
    dob: "1999-12-25",
    gender: "Male",
    imageUrl:
      "https://images.unsplash.com/photo-1488161628813-04466f872be2?w=400",
    bio: "Reggae and Dancehall artist bringing the island vibes.",
    genres: ["Reggae", "Dancehall"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    contact: {
      email: "zion@vibes.com",
      phone: "555-0110",
      location: "Kingston, JM",
    },
    socials: {
      soundcloud: "https://soundcloud.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
      apple: "https://apple.com",
    },
    updatedAt: new Date(),
  },
];

export const seedDatabase = async () => {
  const batch = writeBatch(db);
  SEED_USERS.forEach((u) => batch.set(doc(db, "users", u.uid), u));
  await batch.commit();
  alert("Database Seeded!");
};
